target_dir = "~"

[targets]
".yabairc" = { tags = ["macos"] }
".zshrc" = { tags = ["macos", "macos-work"] }
".tmux.conf" = { tags = ["linux", "macos", "tmux"]}

".config/Default.smsetting_app" = { tags = ["macos", "macos-work"] }
".config/skhd" = { tags = ["macos"] }

".config/nvim" = { tags = ["macos", "macos-work", "linux", "nvim"] }
".config/fish" = { tags = ["macos",  "macos-work", "linux", "fish"] }
".config/git" = { tags = ["macos", "linux", "git"] }
".config/kitty" = { tags = ["macos","linux","kitty"] }
".claude" = { tags = ["macos", "linux", "claude"] }

".config/hypr" = { tags = ["linux"] }
".config/waybar" = { tags = ["linux"] }
