[language-server.rust-analyzer]
config = { check = { command = "clippy" } }


[[language]]
name = "python"
language-servers = [ "pyright" ]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true


[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true


[[language]]
name = "nix"
scope = "source.nix"
file-types = ["nix"]
roots = ["flake.nix", "flake.lock"]
auto-format = true # Optional: auto-format on save
formatter = { command = "alejandra", args = ["-"] }


[language-server.iwe]
command = "iwes"


[[language]]
name = "markdown"
language-servers = [ "iwe" ]
auto-format = true



