[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c2c292"

[colors.cursor]
cursor = "#9e9e9e"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[cursor]
blink_interval = 600

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-e", "zsh", "-l"]
program = "/opt/homebrew/bin/zsh"

[[keyboard.bindings]]
chars = "\u0000v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00001"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00002"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00003"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00004"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00005"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00006"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00007"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00008"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00009"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000L"
key = "Right"
mods = "Command"

[scrolling]
history = 0

[shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux attach|| /opt/homebrew/bin/tmux"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.92
startup_mode = "Windowed"
title = "SMC"

[window.dimensions]
columns = 80
lines = 25
