theme = "moonfly"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes = true
scrolloff = 5
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
completion-trigger-len = 1
popup-border = "all"
jump-label-alphabet = "tnseridhplfu"
end-of-line-diagnostics = "hint"
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ">"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.lsp]
auto-signature-help = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

[keys.normal.space.space]
r = ":config-reload"
# f = "file_browser"
