[language-server.rust-analyzer]
config = { check = { command = "clippy" } }


[[language]]
name = "python"
language-servers = [ "pyright" ]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true


[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true


[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true
